---
layout: default
title: "CFP: AI-SDLC"
description: "CFP: Envisioning the AI-Augmented Software Development Life Cycle"
nav_order: 3
---

# Call for papers, Envisioning the AI-Augmented Software Development Life Cycle
{: .fs-9 }

The Special Issue in the Automated Software Engineering Journal showcases the research focused on envisioning the AI-Augmented Software Development Life Cycle (AI-SDLC). This special issue invites selected papers from the AI-SDLC Workshop, collocated with FSE 2025 to submit extended versions for consideration as well as other authors to share significant, original, and unpublished results within these areas. Submissions will undergo a rigorous peer-review process to maintain the journal’s high standards. 

The goal of the special issue is to explore how AI (including but not limited to generative AI) might (if at all) transform end-to-end software systems development workflows?
Papers which demonstrate research results and case studies describing the changing landscape of software development and identify evidence on key activities which demonstrate different or augmented life cycle activities with AI-based tools are key focus of the issue. 

Topics of Interest include, but are not limited to:
-	How to deal with the quality and impact of the unexpectedly large volumes of code generated by AI-augmented tools, 
-	How to ensure consistency of generated code across a large code base and other development artifacts through the development life cycle
-	What key artifacts are essential to support software development and deployment with AI-based tools
-	How and whether workflows of different software development activities change with use of AI-based tools
-	What is the return on investment on using AI-based tools 
-	Evidence against risk and gains of using AI-based tools 


## Deadline

Opening date for submissions: September 1, 2025

## How to Submit

Please submit via [Springer](https://link.springer.com/collections/ijcbbcddgh).

## Editor

Guest editor list: 
- Ipek Ozkaya, ozkaya@sei.cmu.edu, Software Engineering Institute, Carnegie Mellon University, Pittsburgh, PA USA
- Anita Carleton, adc@sei.cmu.edu, Software Engineering Institute, Carnegie Mellon University, Pittsburgh, PA USA
- Heiko Koziolek, heiko@koziolek.de, Corporate Research, ABB, Ladenburg, Germany
- David Lo, davidlo@smu.edu.sg, Singapore Management University, Singapore
- Douglas C. Schmidt, dcschmidt@wm.edu, William & Mary, Williamsburg, VA, US
