title: "Automated Software Engineering Journal (companion site)"
description: Extra information on the ASE journal
remote_theme: just-the-docs/just-the-docs
logo: "/img/logo.png"
favicon_ico: "/img/favicon.ico"
color_scheme: dark
