title: "About ASE Journal"
description: Extra information on the ASE journal
remote_theme: just-the-docs/just-the-docs
xlogo: "/img/logo.png"
favicon_ico: "/img/favicon.ico"
color_scheme: dark
gh_edit_link: true # show or hide edit this page link
gh_edit_link_text: "Edit this page on GitHub."
gh_edit_repository: "https://github.com/ause-journal/ause-journal.github.io" # the github URL for your repo
gh_edit_branch: "main" # the branch that your docs is served from
# gh_edit_source: docs # the source that your files originate from
gh_edit_view_mode: "tree" # "tree" or "edit" if you want the user to jump into the editor immediately

